### PR TITLE
Added a_mysql.cson in snippets

### PR DESCRIPTION
**Pull request by George480**
BlueG's MySQL Plugin, version R41 and above.

### CODE REVIEW

**Comment by George480** [comment]
There are certain functions that are missing. Shall we add them?

 * core.inc
   * `heapspace`
   * `funcidx`
   * `numargs`
   * `getarg`
   * `setarg`
   * `swapchars`
   * `min`
   * `max`
   * `clamp`
   * `getproperty`
   * `setproperty`
   * `deleteproperty`
   * `existproperty`
 * string.inc
   * `memcpy`
   * `uudecode`
   * `uuencode`

I  also noticed in string functions where last parameter is `maxlength=sizeof dest`, the auto-completion does not include it. Community compiler returns correct value for enum-arrays but default compiler is not.

**Comment by wuzi** [comment]
Thanks for the PR.
Yes, specially because they are standard functions i think it would be good to have them.

**Comment by George480** [comment]
I will add new functions for streamer.cson tomorrow. Is there any other include you may want to add?

PS: I installed Atom yesterday and managed to get the compiler working today. I really like the editor combined with your package! Thank you.

**Comment by wuzi** [comment]
Not atm.
I'll merge this one, feel free to create a new one if you add new functions.

**Pull request merged**
